version: '3.8'
services:
  home-db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      POSTGRES_DB: home-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5430:5432'