server:
  port: 8678
  address: localhost

spring:
  datasource:
    password: postgres
    username: postgres
    url: jdbc:postgresql://localhost:5430/home-db
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        show_sql: false
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: create
    generate-ddl: true